"""add conversation activity

Revision ID: 463b2ce3fc64
Revises: 6c03159077a5
Create Date: 2026-09-03 12:08:24.317866

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "463b2ce3fc64"
down_revision: str | Sequence[str] | None = "6c03159077a5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "conversation_activity",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("conversation_ref", sa.String(length=64), nullable=False),
        sa.Column("property_slug", sa.String(length=128), nullable=True),
        sa.Column("source", sa.String(length=64), nullable=True),
        sa.Column("booking_status", sa.String(length=32), nullable=True),
        sa.Column("last_message_at", sa.String(length=32), nullable=True),
        sa.Column("last_message_sender", sa.String(length=32), nullable=True),
        sa.Column("message_count", sa.Integer(), nullable=False),
        sa.Column("conversation_fingerprint", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("first_seen_at", sa.String(length=32), nullable=False),
        sa.Column("last_refreshed_at", sa.String(length=32), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("conversation_activity", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_conversation_activity_conversation_ref"),
            ["conversation_ref"],
            unique=True,
        )
        batch_op.create_index(
            batch_op.f("ix_conversation_activity_last_message_at"),
            ["last_message_at"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_conversation_activity_status"), ["status"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("conversation_activity", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_conversation_activity_status"))
        batch_op.drop_index(batch_op.f("ix_conversation_activity_last_message_at"))
        batch_op.drop_index(batch_op.f("ix_conversation_activity_conversation_ref"))

    op.drop_table("conversation_activity")
    # ### end Alembic commands ###
