"""add conversation drafts

Revision ID: 6c03159077a5
Revises: 6ed2bd650d7d
Create Date: 2026-09-03 08:34:03.127526

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6c03159077a5"
down_revision: str | Sequence[str] | None = "6ed2bd650d7d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "conversation_drafts",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("draft_ref", sa.String(length=64), nullable=False),
        sa.Column("conversation_ref", sa.String(length=32), nullable=False),
        sa.Column("property_slug", sa.String(length=120), nullable=True),
        sa.Column("conversation_fingerprint", sa.String(length=64), nullable=False),
        sa.Column("subject", sa.String(length=200), nullable=True),
        sa.Column("message", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("detail", sa.Text(), nullable=True),
        sa.Column("source_run_id", sa.String(length=36), nullable=True),
        sa.Column("created_at", sa.String(length=40), nullable=False),
        sa.Column("updated_at", sa.String(length=40), nullable=False),
        sa.Column("edited_at", sa.String(length=40), nullable=True),
        sa.Column("sent_at", sa.String(length=40), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("conversation_drafts", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_conversation_drafts_conversation_fingerprint"),
            ["conversation_fingerprint"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_conversation_drafts_conversation_ref"),
            ["conversation_ref"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_conversation_drafts_draft_ref"), ["draft_ref"], unique=True
        )
        batch_op.create_index(
            batch_op.f("ix_conversation_drafts_source_run_id"),
            ["source_run_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_conversation_drafts_status"), ["status"], unique=False
        )

    # Autogenerate also proposed dropping the server_defaults on
    # hospitality_knowledge. Removed deliberately: those defaults exist so a
    # future NOT NULL column can be added to a populated table, and stripping
    # them is unrelated churn this migration has no business doing.


def downgrade() -> None:
    """Downgrade schema."""
    with op.batch_alter_table("conversation_drafts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_conversation_drafts_status"))
        batch_op.drop_index(batch_op.f("ix_conversation_drafts_source_run_id"))
        batch_op.drop_index(batch_op.f("ix_conversation_drafts_draft_ref"))
        batch_op.drop_index(batch_op.f("ix_conversation_drafts_conversation_ref"))
        batch_op.drop_index(
            batch_op.f("ix_conversation_drafts_conversation_fingerprint")
        )

    op.drop_table("conversation_drafts")
    # ### end Alembic commands ###
