"""add knowledge audience and safety status

Revision ID: 6ed2bd650d7d
Revises: 943c61da2fe5
Create Date: 2026-09-03 01:46:37.706835

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6ed2bd650d7d"
down_revision: str | Sequence[str] | None = "943c61da2fe5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # Adjusted from the autogenerated draft: these are NOT NULL columns added to
    # a table that already holds rows, so each needs a server_default or the
    # upgrade fails on the existing data. The defaults are the conservative
    # values -- an existing row predates audience classification, so it is
    # treated as internal until something says otherwise.
    with op.batch_alter_table("hospitality_knowledge", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "audience",
                sa.String(length=20),
                nullable=False,
                server_default="INTERNAL_OPERATION",
            )
        )
        batch_op.add_column(
            sa.Column(
                "safety_status",
                sa.String(length=30),
                nullable=False,
                server_default="SAFE",
            )
        )
        batch_op.add_column(
            sa.Column(
                "safety_reasons_json",
                sa.Text(),
                nullable=False,
                server_default="[]",
            )
        )
        batch_op.create_index(
            batch_op.f("ix_hospitality_knowledge_audience"), ["audience"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_hospitality_knowledge_safety_status"),
            ["safety_status"],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("hospitality_knowledge", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_hospitality_knowledge_safety_status"))
        batch_op.drop_index(batch_op.f("ix_hospitality_knowledge_audience"))
        batch_op.drop_column("safety_reasons_json")
        batch_op.drop_column("safety_status")
        batch_op.drop_column("audience")

    # ### end Alembic commands ###
