"""add hospitality knowledge

Revision ID: 943c61da2fe5
Revises: a96f06b2a059
Create Date: 2026-09-03 01:28:49.904311

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "943c61da2fe5"
down_revision: str | Sequence[str] | None = "a96f06b2a059"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "hospitality_knowledge",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("knowledge_ref", sa.String(length=64), nullable=False),
        sa.Column("property_slug", sa.String(length=120), nullable=True),
        sa.Column("topic", sa.String(length=60), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("source_type", sa.String(length=30), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("evidence_count", sa.Integer(), nullable=False),
        sa.Column("evidence_property_count", sa.Integer(), nullable=False),
        sa.Column("evidence_refs_json", sa.Text(), nullable=False),
        sa.Column("first_observed_at", sa.String(length=40), nullable=True),
        sa.Column("last_observed_at", sa.String(length=40), nullable=True),
        sa.Column("created_at", sa.String(length=40), nullable=False),
        sa.Column("updated_at", sa.String(length=40), nullable=False),
        sa.Column("decided_at", sa.String(length=40), nullable=True),
        sa.Column("decided_by_user_id", sa.String(length=36), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("hospitality_knowledge", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_hospitality_knowledge_decided_by_user_id"),
            ["decided_by_user_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_hospitality_knowledge_knowledge_ref"),
            ["knowledge_ref"],
            unique=True,
        )
        batch_op.create_index(
            batch_op.f("ix_hospitality_knowledge_property_slug"),
            ["property_slug"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_hospitality_knowledge_status"), ["status"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_hospitality_knowledge_topic"), ["topic"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("hospitality_knowledge", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_hospitality_knowledge_topic"))
        batch_op.drop_index(batch_op.f("ix_hospitality_knowledge_status"))
        batch_op.drop_index(batch_op.f("ix_hospitality_knowledge_property_slug"))
        batch_op.drop_index(batch_op.f("ix_hospitality_knowledge_knowledge_ref"))
        batch_op.drop_index(batch_op.f("ix_hospitality_knowledge_decided_by_user_id"))

    op.drop_table("hospitality_knowledge")
    # ### end Alembic commands ###
