"""add historical reply examples

Revision ID: a96f06b2a059
Revises: 76301e651eea
Create Date: 2026-09-03 01:09:26.290181

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a96f06b2a059"
down_revision: str | Sequence[str] | None = "76301e651eea"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "historical_reply_examples",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("example_ref", sa.String(length=64), nullable=False),
        sa.Column("property_slug", sa.String(length=120), nullable=True),
        sa.Column("source", sa.String(length=40), nullable=True),
        sa.Column("guest_text", sa.Text(), nullable=False),
        sa.Column("owner_text", sa.Text(), nullable=False),
        sa.Column("topics_json", sa.Text(), nullable=False),
        sa.Column("created_at", sa.String(length=40), nullable=True),
        sa.Column("indexed_at", sa.String(length=40), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("historical_reply_examples", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_historical_reply_examples_created_at"),
            ["created_at"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_historical_reply_examples_example_ref"),
            ["example_ref"],
            unique=True,
        )
        batch_op.create_index(
            batch_op.f("ix_historical_reply_examples_property_slug"),
            ["property_slug"],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("historical_reply_examples", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_historical_reply_examples_property_slug"))
        batch_op.drop_index(batch_op.f("ix_historical_reply_examples_example_ref"))
        batch_op.drop_index(batch_op.f("ix_historical_reply_examples_created_at"))

    op.drop_table("historical_reply_examples")
    # ### end Alembic commands ###
