"""Baseline AgentGuard schema.

The schema as it stood when Alembic was adopted, covering every table created
by create_all() up to that point: users, runs, run_steps, approvals,
audit_events and migration_batches.

Autogenerated from the SQLAlchemy models against an empty database, then
reviewed column by column against app/db_models.py.

This migration creates structure only. It seeds no users, no demo batches and
no application data -- seeding is a separate, explicit step.

Revision ID: baa1819ad1d6
Revises:
Create Date: 2026-09-02

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "baa1819ad1d6"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Create the full baseline schema on an empty database."""
    op.create_table(
        "approvals",
        sa.Column("approval_id", sa.String(length=36), nullable=False),
        sa.Column("run_id", sa.String(length=36), nullable=False),
        sa.Column("requested_by_user_id", sa.String(length=36), nullable=True),
        sa.Column("resolved_by_user_id", sa.String(length=36), nullable=True),
        sa.Column("tool_call_id", sa.String(length=100), nullable=False),
        sa.Column("tool", sa.String(length=100), nullable=False),
        sa.Column("arguments_json", sa.Text(), nullable=False),
        sa.Column("risk", sa.String(length=30), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.String(length=40), nullable=False),
        sa.Column("resolved_at", sa.String(length=40), nullable=True),
        sa.Column("decision", sa.String(length=20), nullable=True),
        sa.PrimaryKeyConstraint("approval_id"),
    )
    with op.batch_alter_table("approvals", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_approvals_requested_by_user_id"),
            ["requested_by_user_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_approvals_resolved_by_user_id"),
            ["resolved_by_user_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_approvals_run_id"), ["run_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_approvals_status"), ["status"], unique=False
        )

    op.create_table(
        "audit_events",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("run_id", sa.String(length=36), nullable=True),
        sa.Column("actor_user_id", sa.String(length=36), nullable=True),
        sa.Column("event_type", sa.String(length=50), nullable=False),
        sa.Column("details_json", sa.Text(), nullable=False),
        sa.Column("created_at", sa.String(length=40), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("audit_events", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_audit_events_actor_user_id"), ["actor_user_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_audit_events_run_id"), ["run_id"], unique=False
        )

    op.create_table(
        "migration_batches",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("batch_id", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("records", sa.Integer(), nullable=False),
        sa.Column("duration_seconds", sa.Integer(), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("created_at", sa.String(length=40), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("migration_batches", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_migration_batches_batch_id"), ["batch_id"], unique=True
        )
        batch_op.create_index(
            batch_op.f("ix_migration_batches_status"), ["status"], unique=False
        )

    op.create_table(
        "run_steps",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("run_id", sa.String(length=36), nullable=False),
        sa.Column("step_number", sa.Integer(), nullable=False),
        sa.Column("step_type", sa.String(length=30), nullable=False),
        sa.Column("tool_name", sa.String(length=100), nullable=True),
        sa.Column("arguments_json", sa.Text(), nullable=True),
        sa.Column("result_json", sa.Text(), nullable=True),
        sa.Column("error_json", sa.Text(), nullable=True),
        sa.Column("created_at", sa.String(length=40), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("run_steps", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_run_steps_run_id"), ["run_id"], unique=False
        )

    op.create_table(
        "runs",
        sa.Column("run_id", sa.String(length=36), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("requested_by_user_id", sa.String(length=36), nullable=True),
        sa.Column("user_message", sa.Text(), nullable=False),
        sa.Column("final_answer", sa.Text(), nullable=True),
        sa.Column("conversation_json", sa.Text(), nullable=False),
        sa.Column("created_at", sa.String(length=40), nullable=False),
        sa.Column("updated_at", sa.String(length=40), nullable=False),
        sa.PrimaryKeyConstraint("run_id"),
    )
    with op.batch_alter_table("runs", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_runs_requested_by_user_id"),
            ["requested_by_user_id"],
            unique=False,
        )
        batch_op.create_index(batch_op.f("ix_runs_status"), ["status"], unique=False)

    op.create_table(
        "users",
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("display_name", sa.String(length=120), nullable=False),
        sa.Column("password_hash", sa.String(length=200), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.String(length=40), nullable=False),
        sa.PrimaryKeyConstraint("user_id"),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_users_email"), ["email"], unique=True)
        batch_op.create_index(batch_op.f("ix_users_role"), ["role"], unique=False)


def downgrade() -> None:
    """Drop every table this migration created."""
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_role"))
        batch_op.drop_index(batch_op.f("ix_users_email"))

    op.drop_table("users")
    with op.batch_alter_table("runs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_runs_status"))
        batch_op.drop_index(batch_op.f("ix_runs_requested_by_user_id"))

    op.drop_table("runs")
    with op.batch_alter_table("run_steps", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_run_steps_run_id"))

    op.drop_table("run_steps")
    with op.batch_alter_table("migration_batches", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_migration_batches_status"))
        batch_op.drop_index(batch_op.f("ix_migration_batches_batch_id"))

    op.drop_table("migration_batches")
    with op.batch_alter_table("audit_events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_audit_events_run_id"))
        batch_op.drop_index(batch_op.f("ix_audit_events_actor_user_id"))

    op.drop_table("audit_events")
    with op.batch_alter_table("approvals", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_approvals_status"))
        batch_op.drop_index(batch_op.f("ix_approvals_run_id"))
        batch_op.drop_index(batch_op.f("ix_approvals_resolved_by_user_id"))
        batch_op.drop_index(batch_op.f("ix_approvals_requested_by_user_id"))

    op.drop_table("approvals")
